apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    run: kibana
status:
  loadBalancer: {}
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:7.9.2
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
status: {}
