apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
    name: kibana
  - port: 80
    protocol: TCP
    targetPort: 5601
    name: http
  selector:
    run: kibana
