apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  labels:
    k8s-app: metricbeat
data:
  # This module requires `kube-state-metrics` up and running under `monitoring` namespace
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - state_resourcequota
        - event
      period: 10s
      hosts: ["kube-state-metrics:8080"]