# Deploy singleton instance in the whole cluster for some unique data sources, like kube-state-metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  labels:
    k8s-app: apm-server
spec:
  selector:
    matchLabels:
      k8s-app: apm-server
  template:
    metadata:
      labels:
        k8s-app: apm-server
    spec:
      serviceAccountName: apm-server
      containers:
      - name: apm-server
        image: docker.elastic.co/apm/apm-server:7.9.2
        ports:
        - containerPort: 8200
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/apm-server/apm-server.yml
          readOnly: true
          subPath: apm-server.yml
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: apm-server-config
