apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: apm-server
spec:
  type: ClusterIP
  ports:
  - port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app: apm-server